/*Buenos Aires description taken from: http://www.unepfi.org/regionalroundtable/la-logistics/
**History taken from: https://www.britannica.com/place/Buenos-Aires/History
**All other descriptions from Wikipedia.*/
INSERT INTO City (CityName, CityPopulation, CityDescription, CityCountry, CityHistory, CityLanguage, CityImage) VALUES ('Buenos Aires',14902908,'Buenos Aires, is Argentina’s big, cosmopolitan capital city. Its center is the Plaza de Mayo, lined with stately 19th-century buildings including Casa Rosada, the iconic, balconied presidential palace. Other major attractions include Teatro Colón, a grand 1908 opera house with nearly 2,500 seats, and the modern MALBA museum, displaying Latin American art.','Argentina','The city of Buenos Aires was founded twice. It was first founded in 1536 by an expedition led by the Spaniard Pedro de Mendoza, who named it Nuestra Señora Santa María del Buen Aire (“Our Lady St. Mary of the Good Air”). He was made the first governor-general of the Río de la Plata region.','Spanish','bsas');
INSERT INTO City (CityName, CityPopulation, CityDescription, CityCountry, CityHistory, CityLanguage, CityImage) VALUES ('Las Vegas',632912,'Las Vegas, officially the City of Las Vegas and often known simply as Vegas, is the 28th-most populated city in the United States, the most populated city in the state of Nevada, and the county seat of Clark County. The city anchors the Las Vegas Valley metropolitan area and is the largest city within the greater Mojave Desert. Las Vegas is an internationally renowned major resort city, known primarily for its gambling, shopping, fine dining, entertainment, and nightlife. The Las Vegas Valley as a whole serves as the leading financial, commercial, and cultural center for Nevada.','U.S.A','Las Vegas was founded as a city in 1905, when 110 acres (45 ha) of land adjacent to the Union Pacific Railroad tracks were auctioned in what would become the downtown area. In 1911, Las Vegas was incorporated as a city.','English','vegas');
INSERT INTO City (CityName, CityPopulation, CityDescription, CityCountry, CityHistory, CityLanguage, CityImage) VALUES ('Melbourne',4820000,' Melbourne is the capital and most populous city of the Australian state of Victoria, and the second-most populous city in Australia and Oceania. The name Melbourne refers to an urban agglomeration spanning 9,900 km2 (3,800 sq mi), which comprises the broader metropolitan area, as well as being the common name for its city centre. The metropolis is located on the large natural bay of Port Phillip and expands into the hinterlands towards the Dandenong and Macedon mountain ranges, Mornington Peninsula and Yarra Valley.','Australia','Founded by free settlers from the British Crown colony of Van Diemen''s Land on 30 August 1835, in what was then the colony of New South Wales, it was incorporated as a Crown settlement in 1837. It was named Melbourne by the Governor of New South Wales, Sir Richard Bourke, in honour of the British Prime Minister of the day, William Lamb, 2nd Viscount Melbourne. It was officially declared a city by Queen Victoria, to whom Lord Melbourne was close, in 1847, after which it became the capital of the newly founded colony of Victoria in 1851.','English','melbourne');
INSERT INTO City (CityName, CityPopulation, CityDescription, CityCountry, CityHistory, CityLanguage, CityImage) VALUES ('Dublin',1904806,'Dublin is the capital and largest city of Ireland. Dublin is in the province of Leinster on Ireland''s east coast, at the mouth of the River Liffey. The city is one of the top destinations in the world known for its literary history.','Ireland','Founded as a Viking settlement, the Kingdom of Dublin became Ireland''s principal city following the Norman invasion. The city expanded rapidly from the 17th century and was briefly the second largest city in the British Empire before the Acts of Union in 1800. Following the partition of Ireland in 1922, Dublin became the capital of the Irish Free State, later renamed Ireland.','English','dublin');

INSERT INTO Amenity (AmenityName, AmenityIcon) VALUES ("Pool", "amenity_pool");
INSERT INTO Amenity (AmenityName, AmenityIcon) VALUES ("Wifi", "amenity_wifi");
INSERT INTO Amenity (AmenityName, AmenityIcon) VALUES ("Restaurant", "amenity_restautant");
INSERT INTO Amenity (AmenityName, AmenityIcon) VALUES ("Gym", "amenity_gym");
INSERT INTO Amenity (AmenityName, AmenityIcon) VALUES ("24h Reception", "amenity_24h");
INSERT INTO Amenity (AmenityName, AmenityIcon) VALUES ("Lounge", "amenity_lounge");
INSERT INTO Amenity (AmenityName, AmenityIcon) VALUES ("Parking", "amenity_parking");
INSERT INTO Amenity (AmenityName, AmenityIcon) VALUES ("Valet", "amenity_valet");
INSERT INTO Amenity (AmenityName, AmenityIcon) VALUES ("Concierge", "amenity_concierge");
INSERT INTO Amenity (AmenityName, AmenityIcon) VALUES ("Room Service", "amenity_roomservice");
INSERT INTO Amenity (AmenityName, AmenityIcon) VALUES ("Wheelchair Access", "amenity_wheelchair");
INSERT INTO Amenity (AmenityName, AmenityIcon) VALUES ("Breakfast", "amenity_breakfast");
INSERT INTO Amenity (AmenityName, AmenityIcon) VALUES ("Air Conditioning", "amenity_aircon");
INSERT INTO Amenity (AmenityName, AmenityIcon) VALUES ("Mini Bar", "amenity_minibar");
INSERT INTO Amenity (AmenityName, AmenityIcon) VALUES ("Laundry Service", "amenity_laundry");

INSERT INTO Transport (TransportType, TransportIcon) VALUES ("Bus", "transport_bus");
INSERT INTO Transport (TransportType, TransportIcon) VALUES ("Rail", "transport_rail");
INSERT INTO Transport (TransportType, TransportIcon) VALUES ("Taxi", "transport_taxi");
INSERT INTO Transport (TransportType, TransportIcon) VALUES ("Tram", "transport_tram");
INSERT INTO Transport (TransportType, TransportIcon) VALUES ("Metro", "transport_metro");
INSERT INTO Transport (TransportType, TransportIcon) VALUES ("Monorail", "transport_monorail");
INSERT INTO Transport (TransportType, TransportIcon) VALUES ("Bike", "transport_bike");

INSERT INTO TransportSystem (CityID, TransportID) VALUES (4,1);
INSERT INTO TransportSystem (CityID, TransportID) VALUES (4,2);
INSERT INTO TransportSystem (CityID, TransportID) VALUES (4,3);
INSERT INTO TransportSystem (CityID, TransportID) VALUES (4,4);
INSERT INTO TransportSystem (CityID, TransportID) VALUES (1,1);
INSERT INTO TransportSystem (CityID, TransportID) VALUES (1,2);
INSERT INTO TransportSystem (CityID, TransportID) VALUES (1,3);
INSERT INTO TransportSystem (CityID, TransportID) VALUES (1,5);
INSERT INTO TransportSystem (CityID, TransportID) VALUES (3,1);
INSERT INTO TransportSystem (CityID, TransportID) VALUES (3,2);
INSERT INTO TransportSystem (CityID, TransportID) VALUES (3,3);
INSERT INTO TransportSystem (CityID, TransportID) VALUES (3,4);
INSERT INTO TransportSystem (CityID, TransportID) VALUES (4,7);
INSERT INTO TransportSystem (CityID, TransportID) VALUES (3,7);
INSERT INTO TransportSystem (CityID, TransportID) VALUES (2,1);
INSERT INTO TransportSystem (CityID, TransportID) VALUES (2,3);
INSERT INTO TransportSystem (CityID, TransportID) VALUES (2,4);
INSERT INTO TransportSystem (CityID, TransportID) VALUES (2,6);

INSERT INTO Cuisine (CuisineName) VALUES ('American');
INSERT INTO Cuisine (CuisineName) VALUES ('Arab');
INSERT INTO Cuisine (CuisineName) VALUES ('Argentinian');
INSERT INTO Cuisine (CuisineName) VALUES ('Armenian');
INSERT INTO Cuisine (CuisineName) VALUES ('Asian Fusion');
INSERT INTO Cuisine (CuisineName) VALUES ('Bar');
INSERT INTO Cuisine (CuisineName) VALUES ('Bolivian');
INSERT INTO Cuisine (CuisineName) VALUES ('Brazilian');
INSERT INTO Cuisine (CuisineName) VALUES ('British');
INSERT INTO Cuisine (CuisineName) VALUES ('Café');
INSERT INTO Cuisine (CuisineName) VALUES ('Caribbean');
INSERT INTO Cuisine (CuisineName) VALUES ('Chilean');
INSERT INTO Cuisine (CuisineName) VALUES ('Chinese');
INSERT INTO Cuisine (CuisineName) VALUES ('Cocktails');
INSERT INTO Cuisine (CuisineName) VALUES ('Colombian');
INSERT INTO Cuisine (CuisineName) VALUES ('Dessert');
INSERT INTO Cuisine (CuisineName) VALUES ('Eastern European');
INSERT INTO Cuisine (CuisineName) VALUES ('European');
INSERT INTO Cuisine (CuisineName) VALUES ('Fast Food');
INSERT INTO Cuisine (CuisineName) VALUES ('French');
INSERT INTO Cuisine (CuisineName) VALUES ('Greek');
INSERT INTO Cuisine (CuisineName) VALUES ('Hungarian');
INSERT INTO Cuisine (CuisineName) VALUES ('Ice Cream');
INSERT INTO Cuisine (CuisineName) VALUES ('Indian');
INSERT INTO Cuisine (CuisineName) VALUES ('International');
INSERT INTO Cuisine (CuisineName) VALUES ('Irish');
INSERT INTO Cuisine (CuisineName) VALUES ('Italian');
INSERT INTO Cuisine (CuisineName) VALUES ('Japanese');
INSERT INTO Cuisine (CuisineName) VALUES ('Jewish');
INSERT INTO Cuisine (CuisineName) VALUES ('Korean');
INSERT INTO Cuisine (CuisineName) VALUES ('Latin');
INSERT INTO Cuisine (CuisineName) VALUES ('Lebanese');
INSERT INTO Cuisine (CuisineName) VALUES ('Mediterranean');
INSERT INTO Cuisine (CuisineName) VALUES ('Middle Eastern');
INSERT INTO Cuisine (CuisineName) VALUES ('Mongolian');
INSERT INTO Cuisine (CuisineName) VALUES ('Moroccan');
INSERT INTO Cuisine (CuisineName) VALUES ('Peruvian');
INSERT INTO Cuisine (CuisineName) VALUES ('Polish');
INSERT INTO Cuisine (CuisineName) VALUES ('Portuguese');
INSERT INTO Cuisine (CuisineName) VALUES ('Russian');
INSERT INTO Cuisine (CuisineName) VALUES ('Scandinavian');
INSERT INTO Cuisine (CuisineName) VALUES ('South American');
INSERT INTO Cuisine (CuisineName) VALUES ('Spanish');
INSERT INTO Cuisine (CuisineName) VALUES ('Thai');
INSERT INTO Cuisine (CuisineName) VALUES ('Turkish');
INSERT INTO Cuisine (CuisineName) VALUES ('Vegan');
INSERT INTO Cuisine (CuisineName) VALUES ('Vegetarian');
INSERT INTO Cuisine (CuisineName) VALUES ('Venezualan');
INSERT INTO Cuisine (CuisineName) VALUES ('Vietnamese');
INSERT INTO Cuisine (CuisineName) VALUES ('Wine');
INSERT INTO Cuisine (CuisineName) VALUES ('Steakhouse');

/*Sofitel description taken from here: https://www.booking.com/hotel/ar/buenos-aires.html*/
INSERT INTO Hotel (HotelName, CityID, HotelDescription, HotelAddress, HotelNeighbourhood, HotelWebsite, HotelRating, HotelPrice, HotelClass, HotelPhone, HotelImage) VALUES ('VAIN Boutique Hotel',1,'Located in the heart of Palermo Viejo neighborhood, only 15 minutes away from the main tourist attractions, VAIN Boutique Hotel gives the possibility of having another alternative to the noisy BA downtown. It preserves the Porteño neighborhood feeling, combined with a bohemian and avant-garde mixture that can be sensed in the variety of stores, from fashion designers, antique and design furniture to coffee shops, fashion restaurants and bars, along with the traditional ones.','Thames 2226, 1414 Palermo Viejo, Distrito Federal','Palermo Viejo','http://www.vainhotel.com/',4.1,3.1,4,'+54-11-4776-8246','vainhotel');
INSERT INTO Hotel (HotelName, CityID, HotelDescription, HotelAddress, HotelNeighbourhood, HotelWebsite, HotelRating, HotelPrice, HotelClass, HotelPhone, HotelImage) VALUES ('Sofitel Buenos Aires',1,'In an impressive building, Sofitel Buenos Aires is a designer hotel offering plush accommodations in Retiro, the traditional art district.','Arroyo 841, Retiro 1007, Capital Federal','Retiro','http://www.sofitel.com/gb/hotel-3253-sofitel-buenos-aires/index.shtml',4.5,4.3,5,'+54-11-4131-0000','sofitelba');
INSERT INTO Hotel (HotelName, CityID, HotelDescription, HotelAddress, HotelNeighbourhood, HotelWebsite, HotelRating, HotelPrice, HotelClass, HotelPhone, HotelImage) VALUES ('Bulnes Eco Suites',1,'Set in the lively Palermo district, this modern hotel is a 2-minute walk from Bulnes metro station, a 3-minute walk from Alto Palermo Shopping center and 2 km from Museo Nacional de Bellas Artes.','Bulnes 1905, Recoleta 1425, Capital Federal','Recoleta','http://bulnesecosuites.com/',4.4,2.8,4,'+54-11-4829-3300','ecosuites');
INSERT INTO Hotel (HotelName, CityID, HotelDescription, HotelAddress, HotelNeighbourhood, HotelWebsite, HotelRating, HotelPrice, HotelClass, HotelPhone, HotelImage) VALUES ('Pop Hotel',1,'On a tree-lined street in the upmarket Villa Crespo barrio, this colorful budget hotel is a 6-minute walk from Malabia metro station and 7 km from the Museo Nacional de Bellas Artes.','Juan Ramirez de Velasco 793, Villa Crespo 1414, Capital Federal','Villa Crespo','http://www.pophotelsbuenosaires.com/',4.1,2.2,3,'+54-11-4776-6900','pophotel');
INSERT INTO Hotel (HotelName, CityID, HotelDescription, HotelAddress, HotelNeighbourhood, HotelWebsite, HotelRating, HotelPrice, HotelClass, HotelPhone, HotelImage) VALUES ('Four Seasons Buenos Aires',1,'Spread across a tower and a belle epoque mansion, this luxury hotel is 1 km from the Teatro Colón opera house.','Posadas 1086/88, Retiro 1011, Capital Federal','Retiro','http://www.fourseasons.com/buenosaires/',4.6,4.5,5,'+54-11-4321-1200','fourseasons');
INSERT INTO Hotel (HotelName, CityID, HotelDescription, HotelAddress, HotelNeighbourhood, HotelWebsite, HotelRating, HotelPrice, HotelClass, HotelPhone, HotelImage) VALUES ('Hotel Madero',1,'Set 3.4 km from Downtown in the modern waterfront district of Puerto Madero, this sleek art deco-style hotel is also a 14-minute walk from the Museo de Arte Moderno de Buenos Aires.','Dique 2, Rosario Vera Peñaloza 360, 1107 Puerto Madero','Puerto Madero','https://www.hotelmadero.com/',4.4,3.9,5,'+54-11-5776-7777','madero');
INSERT INTO Hotel (HotelName, CityID, HotelDescription, HotelAddress, HotelNeighbourhood, HotelWebsite, HotelRating, HotelPrice, HotelClass, HotelPhone, HotelImage) VALUES ('Alvear Palace Hotel',1,'A 5-minute walk from Centro Cultural Recoleta, this palatial hotel in a grand building is 2 km from Teatro Colón opera house, and 11 minutes walk from La Recoleta Cemetery.','Av. Alvear 1891, 1129 Retiro, Capital Federal','Retiro','http://www.alvearpalace.com',4.7,4.8,5,'+54-11-4808-2100','alvear');
INSERT INTO Hotel (HotelName, CityID, HotelDescription, HotelAddress, HotelNeighbourhood, HotelWebsite, HotelRating, HotelPrice, HotelClass, HotelPhone, HotelImage) VALUES ('Aberdeen Lodge',4,'One of Dublin’s gems, a privately owned lodge located in Sandymount, Dublin 4. Trinity College, the heart of the city, is 7 minutes away by DART (electric tram) or  10 minutes by taxi. Perfect for the discerning traveller, Aberdeen Lodge combines charm, period features and an outstanding personal service that guests rave about.','53-55 Park Ave, Dublin 4, Co Dublin','Ballsbridge','http://aberdeenlodgedublin.com/',4.6,3.9,4,'+353-1-283-8155','ablodge');
INSERT INTO Hotel (HotelName, CityID, HotelDescription, HotelAddress, HotelNeighbourhood, HotelWebsite, HotelRating, HotelPrice, HotelClass, HotelPhone, HotelImage) VALUES ('Sheraton Melbourne Hotel',3,'This upscale high-rise hotel is a 13-minute walk from Federation Square, 1.5 km from the National Gallery of Victoria and 2.1 km from Queen Victoria Market.','27 Little Collins St, Melbourne VIC 3000, Australia','','http://www.sheratonmelbourne.com/',4.3,4.1,5,'+61-3-9290-1000','sheratonmelbourne');
INSERT INTO Hotel (HotelName, CityID, HotelDescription, HotelAddress, HotelNeighbourhood, HotelWebsite, HotelRating, HotelPrice, HotelClass, HotelPhone, HotelImage) VALUES ('Flamingo Las Vegas',2,'Across the street from Caesars Palace, this neon-lit, art deco-style casino hotel opened in 1946, and is the oldest resort on the Strip still in operation. ','3555 S Las Vegas Blvd, Las Vegas, NV 89109','Las Vegas Strip','https://www.caesars.com/flamingo-las-vegas',3.2,1.9,3,'+1-702-733-3111','flamingovegas');

INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (1,2);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (1,15);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (1,9);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (1,14);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (1,6);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (1,12);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (2,1);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (2,2);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (2,3);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (2,4);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (2,5);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (2,6);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (2,7);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (2,8);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (2,9);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (2,10);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (2,11);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (2,12);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (2,13);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (2,14);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (2,15);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (3,2);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (3,3);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (3,5);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (3,6);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (3,7);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (3,9);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (3,10);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (3,11);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (3,12);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (3,15);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (3,13);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (4,2);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (4,15);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (4,9);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (4,13);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (8,7);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (8,12);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (8,10);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (8,2);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (8,15);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (8,6);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (7,1);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (7,2);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (7,3);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (7,4);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (7,5);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (7,6);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (7,7);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (7,8);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (7,9);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (7,10);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (7,11);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (7,12);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (7,13);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (7,14);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (7,15);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (6,1);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (6,2);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (6,3);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (6,4);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (6,5);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (6,6);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (6,9);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (6,11);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (6,13);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (6,14);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (6,15);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (5,1);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (5,2);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (5,3);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (5,4);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (5,5);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (5,6);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (5,7);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (5,8);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (5,9);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (5,10);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (5,11);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (5,12);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (5,13);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (5,14);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (5,15);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (9,1);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (9,2);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (9,3);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (9,4);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (9,5);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (9,6);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (9,7);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (9,8);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (9,9);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (9,10);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (9,11);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (9,13);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (9,14);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (9,15);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (10,1);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (10,2);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (10,3);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (10,4);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (10,5);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (10,6);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (10,7);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (10,8);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (10,9);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (10,10);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (10,11);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (10,13);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (10,14);
INSERT INTO HotelAmenity (HotelID, AmenityID) VALUES (10,15);

/* Descriptions for restaurants taken from the following:
**Chila: http://www.tinyurbankitchen.com/chila-buenos-aires/
**iLatina: https://www.gringoinbuenosaires.com/i-latina-unforgettable-dining-experience-buenos-aires/
**All others written personally or taken from restaurant website.
*/
INSERT INTO RestaurantBar (RestaurantBarName, CityID, RestaurantBarDescription, RestaurantBarAddress, RestaurantBarNeighbourhood, RestaurantBarWebsite, RestaurantBarOpeningHours, RestaurantBarDiningHours, RestaurantBarRating, RestaurantBarPrice, RestaurantBarMichelinStars, RestaurantBarImage, RestaurantBarPhone, RestaurantBarWheelchairAccess) VALUES ('Sarkis',1,'Sarkis is one of the most popular restaurants in Buenos Aires. Sarkis offer Middle Eastern cuisine of a high quality at very reasonable prices. The results, however are long waiting times for a seat. Once you get a table though, you will not be disappointed.','Thames 1101, 1414 Villa Crespo, Distrito Federal','Villa Crespo','https://www.facebook.com/pages/Sarkis/156339884415152','Mon-Sun 12:00-15:00\r\nMon-Sun 20:00-01:00','Mon-Sun 12:00-15:00\r\nMon-Sun 20:00-01:00',4.5,2.2,0,'sarkis','+54-11-4772-4991',1);
INSERT INTO RestaurantBar (RestaurantBarName, CityID, RestaurantBarDescription, RestaurantBarAddress, RestaurantBarNeighbourhood, RestaurantBarWebsite, RestaurantBarOpeningHours, RestaurantBarDiningHours, RestaurantBarRating, RestaurantBarPrice, RestaurantBarMichelinStars, RestaurantBarImage, RestaurantBarPhone, RestaurantBarWheelchairAccess) VALUES ('Hola Jacoba',1,'Situated in the trendy confines of Palermo Soho, Hola Jacoba is a highly popular Jewish restaurant.','Thames 1801, 1414 Palermo Soho, Distrito Federal','Palermo Soho','https://www.facebook.com/holajacoba/','Wed-Sun 12:00-00:00\r\nTue 19:00-00:00','Wed-Sun 12:00-00:00\r\nTue 19:00-00:00',4.5,3.9,0,'holajacoba','+54-11-4833-5858',1);
INSERT INTO RestaurantBar (RestaurantBarName, CityID, RestaurantBarDescription, RestaurantBarAddress, RestaurantBarNeighbourhood, RestaurantBarWebsite, RestaurantBarOpeningHours, RestaurantBarDiningHours, RestaurantBarRating, RestaurantBarPrice, RestaurantBarMichelinStars, RestaurantBarImage, RestaurantBarPhone, RestaurantBarWheelchairAccess) VALUES ('I Latina',1,'Since its opening two years ago, i Latina has been providing the flavors of Latin America to a curious and sophisticated audience. In a beautiful French-style house, in the neighborhood of Villa Crespo 3 Colombian siblings: Santiago, Camilo and Laura Macias, launched a project that involves a 7 course tasting menu that celebrates the unique and electric tastes of Latin America.','Murillo 725, 1414 Villa Crespo, Distrito Federal','Villa Crespo','http://www.ilatinabuenosaires.com/','Tue-Sat 20:00-01:00','Tue-Sat 20:00-01:00',4.7,4.5,0,'ilatina','+54-11-4857-9095',1);
INSERT INTO RestaurantBar (RestaurantBarName, CityID, RestaurantBarDescription, RestaurantBarAddress, RestaurantBarNeighbourhood, RestaurantBarWebsite, RestaurantBarOpeningHours, RestaurantBarDiningHours, RestaurantBarRating, RestaurantBarPrice, RestaurantBarMichelinStars, RestaurantBarImage, RestaurantBarPhone, RestaurantBarWheelchairAccess) VALUES ('Burger Joint',1,'Since opening in 2013, Burger Joint has a claim to have the best burgers in the city. A visit to this Palermo Soho establishment is well worth .the time.','Jorge Luis Borges 1776, 1414 Palermo Soho, Distrito Federal','Palermo Soho','https://www.facebook.com/BurgerJointPalermo','Mon-Sun 12:00-00:00','Mon-Sun 12:00-00:00',4.3,2.1,0,'burgerjoint','+54-11-4833-5151',1);
INSERT INTO RestaurantBar (RestaurantBarName, CityID, RestaurantBarDescription, RestaurantBarAddress, RestaurantBarNeighbourhood, RestaurantBarWebsite, RestaurantBarOpeningHours, RestaurantBarDiningHours, RestaurantBarRating, RestaurantBarPrice, RestaurantBarMichelinStars, RestaurantBarImage, RestaurantBarPhone, RestaurantBarWheelchairAccess) VALUES ('Chila',1,'Chila opened in 2006 in Puerto Madero, a beautiful, newer riverside neighborhood on the modern side of Buenos Aires. It has gorgeous views of the Rio de la Plata and serves new Argentinian cuisine.','Alicia Moreau de Justo 1160, 1107 Puerto Madero, Distrito Federal','Puerto Madero','http://www.chilaweb.com.ar/','Tue-Sun 20:00-23:00','Tue-Sun 20:00-23:00',4.4,4.7,0,'chila','+54-11-4343-6067',1);
INSERT INTO RestaurantBar (RestaurantBarName, CityID, RestaurantBarDescription, RestaurantBarAddress, RestaurantBarNeighbourhood, RestaurantBarWebsite, RestaurantBarOpeningHours, RestaurantBarDiningHours, RestaurantBarRating, RestaurantBarPrice, RestaurantBarMichelinStars, RestaurantBarImage, RestaurantBarPhone, RestaurantBarWheelchairAccess) VALUES ('Vic & Anthony''s Steakhouse',2,'Upscale steakhouse serving meat & seafood with classic salads & side dishes in old-school environs.','129 E Fremont Street, Las Vegas, NV 89101','Downtown','http://www.vicandanthonys.com/locations/las-vegas/index.asp','Mon-Sun 17:00-23:00','Mon-Sun 17:00-23:00',4.6,3.1,0,'vicanthonyvegas','+1-702-386-8399',1);
INSERT INTO RestaurantBar (RestaurantBarName, CityID, RestaurantBarDescription, RestaurantBarAddress, RestaurantBarNeighbourhood, RestaurantBarWebsite, RestaurantBarOpeningHours, RestaurantBarDiningHours, RestaurantBarRating, RestaurantBarPrice, RestaurantBarMichelinStars, RestaurantBarImage, RestaurantBarPhone, RestaurantBarWheelchairAccess) VALUES ('Longrain Restaurant',3,'Spacious rustic-chic Southeast Asian restaurant with cocktail bar, communal tables and share dishes.','44 Little Bourke St, East Melbourne, Melbourne VIC 3000','East Melbourne','https://longrain.com/melbourne','Mon-Thu 18:00-Late\r\nFri-Sun 17:30-Late','Mon-Thu 18:00-Late\r\nFri-Sun 17:30-Late',4.3,2.3,0,'longrainmelbourne','+61-3-9671-3151',1);
INSERT INTO RestaurantBar (RestaurantBarName, CityID, RestaurantBarDescription, RestaurantBarAddress, RestaurantBarNeighbourhood, RestaurantBarWebsite, RestaurantBarOpeningHours, RestaurantBarDiningHours, RestaurantBarRating, RestaurantBarPrice, RestaurantBarMichelinStars, RestaurantBarImage, RestaurantBarPhone, RestaurantBarWheelchairAccess) VALUES ('The Sussex Restaurant',4,'Classy bistro with panelled walls and dark wood floors, for unpretentious seasonal Irish cooking.','8-9 Sussex Terrace, Upper Leeson Street, Dublin 4.','Dublin 4','http://thesussex.ie/','Mon-Fri 12:00-22:00\r\nSat-Sun 17:00-10:00','Mon-Fri 12:00-22:00\r\nSat-Sun 17:00-10:00',4.5,3.8,0,'sussexrestdub','+353-1-538-8100',1);

INSERT INTO RestaurantBarCuisine (RestaurantBarID, CuisineID) VALUES (1,4);
INSERT INTO RestaurantBarCuisine (RestaurantBarID, CuisineID) VALUES (1,34);
INSERT INTO RestaurantBarCuisine (RestaurantBarID, CuisineID) VALUES (1,32);
INSERT INTO RestaurantBarCuisine (RestaurantBarID, CuisineID) VALUES (1,17);
INSERT INTO RestaurantBarCuisine (RestaurantBarID, CuisineID) VALUES (2,29);
INSERT INTO RestaurantBarCuisine (RestaurantBarID, CuisineID) VALUES (2,34);
INSERT INTO RestaurantBarCuisine (RestaurantBarID, CuisineID) VALUES (2,33);
INSERT INTO RestaurantBarCuisine (RestaurantBarID, CuisineID) VALUES (2,17);
INSERT INTO RestaurantBarCuisine (RestaurantBarID, CuisineID) VALUES (3,31);
INSERT INTO RestaurantBarCuisine (RestaurantBarID, CuisineID) VALUES (3,15);
INSERT INTO RestaurantBarCuisine (RestaurantBarID, CuisineID) VALUES (3,42);
INSERT INTO RestaurantBarCuisine (RestaurantBarID, CuisineID) VALUES (4,1);
INSERT INTO RestaurantBarCuisine (RestaurantBarID, CuisineID) VALUES (4,6);
INSERT INTO RestaurantBarCuisine (RestaurantBarID, CuisineID) VALUES (4,19);
INSERT INTO RestaurantBarCuisine (RestaurantBarID, CuisineID) VALUES (5,3);
INSERT INTO RestaurantBarCuisine (RestaurantBarID, CuisineID) VALUES (5,42);
INSERT INTO RestaurantBarCuisine (RestaurantBarID, CuisineID) VALUES (5,25);
INSERT INTO RestaurantBarCuisine (RestaurantBarID, CuisineID) VALUES (6,1);
INSERT INTO RestaurantBarCuisine (RestaurantBarID, CuisineID) VALUES (6,51);
INSERT INTO RestaurantBarCuisine (RestaurantBarID, CuisineID) VALUES (7,5);
INSERT INTO RestaurantBarCuisine (RestaurantBarID, CuisineID) VALUES (7,14);
INSERT INTO RestaurantBarCuisine (RestaurantBarID, CuisineID) VALUES (8,26);

INSERT INTO Airport (AirportName, CityID, AirportIATACode) VALUES ('Ezeiza International Airport',1,'EZE');
INSERT INTO Airport (AirportName, CityID, AirportIATACode) VALUES ('Aeroparque Jorge Newbery',1,'AEP');
INSERT INTO Airport (AirportName, CityID, AirportIATACode) VALUES ('McCarran International Airport',2,'LAS');
INSERT INTO Airport (AirportName, CityID, AirportIATACode) VALUES ('Dublin Airport',4,'DUB');
INSERT INTO Airport (AirportName, CityID, AirportIATACode) VALUES ('Melbourne Airport',3,'MEL');
INSERT INTO Airport (AirportName, CityID, AirportIATACode) VALUES ('Avalon Airport',3,'AVV');
INSERT INTO Airport (AirportName, CityID, AirportIATACode) VALUES ('Essebendon Airport',3,'MEB');
INSERT INTO Airport (AirportName, CityID, AirportIATACode) VALUES ('Moorabbin Airport',3,'MBW');
INSERT INTO Airport (AirportName, CityID, AirportIATACode) VALUES ('North Las Vegas Airport',2,'VGT');

INSERT INTO Event (EventName, CityID, EventDescription, EventAddress, EventWebsite, EventStartDateTime, EventEndDateTime, EventTheme, EventImage, EventWheelchairAccess) VALUES ('Green Day Buenos Aires',1,'Green Day, one of the most  popular bands in the world is visiting Buenos Aires. Come and you will have the Time of Your Life!','Estadio Vélez, Av. Juan B. Justo 9200, Capital Federal','http://www.vuenosairez.com/ar/ciudad-de-buenos-aires/agenda/green-day-en-argentina/164501','10/11/17 16:00','11/11/17 01:00','Music','greendayba',0);
INSERT INTO Event (EventName, CityID, EventDescription, EventAddress, EventWebsite, EventStartDateTime, EventEndDateTime, EventTheme, EventImage, EventWheelchairAccess) VALUES ('Earth, Wind & Fire',2,'Earth, Wind & Fire is an American band that has spanned the musical genres of R&B, soul, funk, jazz, disco, pop, rock, Latin and African. They are one of the most successful bands of all time.','4321 West Flamingo Road, Las Vegas, NV','http://www.bandsintown.com/Earth,WindAndFire','14/07/17 19:00','14/07/17 23:00','Music','ewfvegas',1);
INSERT INTO Event (EventName, CityID, EventDescription, EventAddress, EventWebsite, EventStartDateTime, EventEndDateTime, EventTheme, EventImage, EventWheelchairAccess) VALUES ('International Ballet Gala',3,'The highly successful 2009 International Ballet Gala returns with current and future stars from renowned international ballet companies such as Bolshoi Ballet, Kirov Ballet, American Ballet Theatre and special guest artists performing spectacular dance pieces and great virtuosity in world famous grand pas de deux’s of the classical repertoire supported by dancers of the Australian Conservatoire of Ballet.','Arts Centre Melbourne, 100 Saint Kilda Road, Melbourne VIC','https://www.artscentremelbourne.com.au/whats-on/2017/ballet/international-ballet-gala','15/07/17 19:30','15/07/17 23:00','Ballet','intballetgalamelbourne',1);
INSERT INTO Event (EventName, CityID, EventDescription, EventAddress, EventWebsite, EventStartDateTime, EventEndDateTime, EventTheme, EventImage, EventWheelchairAccess) VALUES ('Rodrigo y Gabriela @ National Concert Hall',4,'Rodrigo y Gabriela celebrate the tenth anniversary re-release of their classic self-titled break-out album with a special performance at the National Concert Hall. Originally released in 2006, the album topped the charts and helped establish the Mexican guitar duo as one of the most popular acoustic instrumental artists in the world.','The National Concert Hall, 2 Earlsfort Terrace, Dublin 2','https://www.nch.ie/Online/Rodrigo-Y-Gabriela-15Jul17','15/07/17 20:00','15/07/17 23:30','Music','rodgabdub',1);

INSERT INTO Tour (TourName, CityID, TourDescription, TourAddress, TourWebsite, TourOperator, TourPrice, TourRating, TourOperatingTimes, TourImage, TourPhone, TourWheelchairAccess) VALUES ('BuenosTours - Buenos Aires Private Walking Tours',1,'Discover the real Buenos Aires up close and personal on a private walking tour. If you have a whole day available, our Full Day Walking Tour is the best way to see the most important sights of the city. Less time? Try a Half Day Tour of the Historical City Center, a concise intro to the city’s fascinating history & culture. ','San Telmo, Capital Federal, Buenos Aires','http://www.buenostours.com/','BuenosTours',1.9,5,'Mon-Sun 08:30-19:30','buenostoura','+54-11-5325-7020',0);
INSERT INTO Tour (TourName, CityID, TourDescription, TourAddress, TourWebsite, TourOperator, TourPrice, TourRating, TourOperatingTimes, TourImage, TourPhone, TourWheelchairAccess) VALUES ('Las Vegas Walking Tours',2,'We know you’re looking for things to do in Las Vegas, why not consider a walking tour! Las Vegas Walking Tours are fun, affordable, informative and quite possibly the best travel activity. Walking tours accommodate families, couples and even the single adventurous traveler while offering the opportunity to meet other travelers from around the world and possibly even make new friends.','Las Vegas, NV 89101, Nevada','https://lasvegaswalkingtours.net/','Las Vegas Walking Tours',3.1,4.3,'Mon-Sat 11:00-16:30\r\nTue,Wed 19:00-21:00\r\nSun14:00-21:00','vegaswalkingtours','+1-702-960-4421',1);
INSERT INTO Tour (TourName, CityID, TourDescription, TourAddress, TourWebsite, TourOperator, TourPrice, TourRating, TourOperatingTimes, TourImage, TourPhone, TourWheelchairAccess) VALUES ('Bunyip Tours Melbourne',3,'From the spectacular Great Ocean Road to the world famous little penguins on Phillip Island, from the pristine beaches of the southernmost region of mainland Australia, Wilsons Promontory to the charming Mornington Peninsula, Bunyip Tours features so many unique places to visit and things to see and do. ','570 Flinders St, Melbourne VIC 3000, Australia','http://www.bunyiptours.com/','Bunyip Tours Melbourne',3.9,4.4,'Mon-Sun 07:00-21:00','bunyiptours','+61-3-9650-9680',1);
INSERT INTO Tour (TourName, CityID, TourDescription, TourAddress, TourWebsite, TourOperator, TourPrice, TourRating, TourOperatingTimes, TourImage, TourPhone, TourWheelchairAccess) VALUES ('Viking Splash Tours',4,'Established in 1999, Viking Splash Tours is one of Ireland’s premier tour companies. Combining authentic World War II amphibious vehicles – the DUKWs – with an imaginative and exciting Viking-themed tour, the Viking Splash experience is unrivalled in Dublin City.','St Stephens Green North, Dublin 2, Dublin','http://www.vikingsplash.com/','Viking Splash Tours',2.2,4.3,'Mon-Sun 09:00-17:00','vikingsplash','+353-1-707-6000',0);

INSERT INTO Attraction (AttractionName, CityID, AttractionDescription, AttractionAddress, AttractionNeighbourhood, AttractionWebsite,AttractionPrice, AttractionRating, AttractionOpeningHours, AttractionImage, AttractionPhone, AttractionWheelchairAccess) VALUES ('Buenos Aires Ecological Reserve',1,'Buenos Aires Ecological Reserve, Reserva Ecológica de Buenos Aires, also known as Costanera Sur Ecological Reserve, Reserva Ecológica Costanera Sur, is a 865-acre (3.50 km2) tract of low land on the Río de la Plata riverbank located on the east side of the district of Puerto Madero in Buenos Aires. Being adjacent to the city, a visit to the Ecological Reserve is an escape from the hustle and bustle of the metropolis. A number of trails leading to the river are perfect for birdwatching, strolling, cycling and nature lovers.','Achaval Rodriguez T., Dr. Av. 1550, Costanera Sur','Consanera Sur','http://www.buenosaires.gob.ar/ambienteyespaciopublico/mantenimiento/espaciosverdes/reservaecologica',0,4.6,'Tue-Sun 08:00-18:00','ecoreserve','+54-11-4893-1853',1);
INSERT INTO Attraction (AttractionName, CityID, AttractionDescription, AttractionAddress, AttractionNeighbourhood, AttractionWebsite,AttractionPrice, AttractionRating, AttractionOpeningHours, AttractionImage, AttractionPhone, AttractionWheelchairAccess) VALUES ('Buenos Aires Japanese Gardens',1,'The Buenos Aires Japanese Gardens are a public space administered by the non-profit Japanese Argentine Cultural Foundation in Buenos Aires, Argentina, and are one of the largest Japanese gardens of its type in the world outside Japan.','Av. Casares 2966, 1425 Palermo, Distrito Federal','Palermo','http://www.jardinjapones.org.ar/',2.1,4.5,'Mon-Sun 10:00-18:00','japanesegardensba','+54-11-4804-4922',1);
INSERT INTO Attraction (AttractionName, CityID, AttractionDescription, AttractionAddress, AttractionNeighbourhood, AttractionWebsite,AttractionPrice, AttractionRating, AttractionOpeningHours, AttractionImage, AttractionPhone, AttractionWheelchairAccess) VALUES ('St Patrick''s Cathedral',4,'Saint Patrick''s Cathedral in Dublin, Ireland, founded in 1191, is the National Cathedral of the Church of Ireland. With its 43-metre spire, St. Patrick''s is the tallest church in Ireland and the largest.','St Patrick''s Close, Wood Quay, Dublin 8','Dublin 8','https://www.stpatrickscathedral.ie/',2.9,4.1,'Mon-Sun 09:00-18:00','stpatscathedral','+353-1-453-9472',1);
INSERT INTO Attraction (AttractionName, CityID, AttractionDescription, AttractionAddress, AttractionNeighbourhood, AttractionWebsite,AttractionPrice, AttractionRating, AttractionOpeningHours, AttractionImage, AttractionPhone, AttractionWheelchairAccess) VALUES ('Sea Life Melbourne Aquarium',3,'Situated on the riverside, just opposite the Crown Casino, Melbourne Aquarium is home to thousands of animals, including sharks, turtles, stingrays, sawfish, tropical fish and much, much more.','King St & Flinders St, Melbourne VIC 3000, Australia','South Wharf','https://www.melbourneaquarium.com.au/',2.5,4.1,'Mon-Sun 09:30-18:00','sealifemelbourne','+61-1800-026-576',1);
INSERT INTO Attraction (AttractionName, CityID, AttractionDescription, AttractionAddress, AttractionNeighbourhood, AttractionWebsite,AttractionPrice, AttractionRating, AttractionOpeningHours, AttractionImage, AttractionPhone, AttractionWheelchairAccess) VALUES ('Fremont Street Experience',2,'Sprawling 24-hour mall featuring a huge LED canopy, casino & restaurant access & free entertainment.','Fremont St, Las Vegas, NV 89101','Downtown','https://vegasexperience.com/',0,4.2,'Open 24 hours.','fremontstexp','+1-702-678-5600',1);
